
version: '3.9'
name: 'bolster'
services:
  postgres:
    container_name: pfh_postgres_db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - /c:/Users/docker/postgresData:/var/lib/postgresql/data
# docker-compose -f .docker/docker-compose.yml --env-file .env up -d
